# https://github.com/kubernetes-sigs/dra-driver-cpu/blob/main/hack/kind.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  DynamicResourceAllocation: true
  DRAResourceClaimDeviceStatus: true
  DRAConsumableCapacity: true
nodes:
- role: control-plane
  image: kindest/node:v1.34.0
- role: worker
  image: kindest/node:v1.34.0
- role: worker
  image: kindest/node:v1.34.0
